// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGChatManager.h"
#include "FGGameState.h"

AFGChatManager* AFGChatManager::Get(UWorld* world) {
	if (world) {
		if (AFGGameState* GameState = Cast<AFGGameState>(world->GetGameState())) {
			return GameState->GetChatManager();
		}
	}
	return nullptr;
}

AFGChatManager* AFGChatManager::Get(UObject* worldContext) {
	if (worldContext) {
		return Get(worldContext->GetWorld());
	}
	return nullptr;
}

AFGChatManager::AFGChatManager() : Super() {
	this->mMaxNumMessagesInHistory = 50;
	this->mMessageVisibleDuration = 10.0;
}

void AFGChatManager::BroadcastChatMessage(const FChatMessageStruct& newMessage, APlayerController* instigatorPlayerController) {
	FChatMessageStruct Message = newMessage;
	if (Message.ServerTimeStamp == 0.0f) {
		UWorld* World = GetWorld();
		if (World) {
			if (AGameStateBase* GameState = World->GetGameState()) {
				Message.ServerTimeStamp = GameState->GetServerWorldTimeSeconds();
			}
		}
	}
	Multicast_BroadcastChatMessage(Message, instigatorPlayerController);
}

void AFGChatManager::AddChatMessageToReceived(const FChatMessageStruct& inMessage) {
	mReceivedMessages.Add(inMessage);
	while (mReceivedMessages.Num() > mMaxNumMessagesInHistory) {
		mReceivedMessages.RemoveAt(0);
	}
	OnChatMessageAdded.Broadcast();
}

void AFGChatManager::GetReceivedChatMessages(TArray< FChatMessageStruct >& out_messages) const {
	out_messages = mReceivedMessages;
}

int32 AFGChatManager::GetMaxNumMessagesInHistory() const {
	return mMaxNumMessagesInHistory;
}

float AFGChatManager::GetMessageVisibleDuration() const {
	return mMessageVisibleDuration;
}

void AFGChatManager::Multicast_BroadcastChatMessage_Implementation(const FChatMessageStruct& newMessage, APlayerController* instigatorPlayerController) {
	AddChatMessageToReceived(newMessage);
}