// This file has been automatically generated by the Unreal Header Implementation tool

#include "Networking/FGServerWebSocketManager.h"

UFGServerWebSocketManager::UFGServerWebSocketManager(){ }
bool UFGServerWebSocketManager::Initialize(int32 WebSocketPort){ return bool(); }
void UFGServerWebSocketManager::Shutdown(){ }
bool UFGServerWebSocketManager::IsRunning() const{ return bool(); }
void UFGServerWebSocketManager::BroadcastMessage(const FString& Message){ }
bool UFGServerWebSocketManager::SendMessageToClient(const FString& ClientId, const FString& Message){ return bool(); }
void UFGServerWebSocketManager::DisconnectClient(const FString& ClientId){ }
UFGServerSubsystem* UFGServerWebSocketManager::GetOuterServerSubsystem() const{ return nullptr; }
void UFGServerWebSocketManager::OnWebSocketClientConnected(INetworkingWebSocket* Socket){ }
void UFGServerWebSocketManager::OnWebSocketRawMessage(const void* Data, int32 Size, int32 BytesRemaining){ }
bool UFGServerWebSocketManager::AuthenticateWebSocketClient(const TMap<FString, FString>& UpgradeHeaders, FString& OutClientId) const{ return bool(); }
